### ISSUE TITLE
Current master fails test.

### ISSUE THREAD

**Issue by perlindgren** [mapeditor/rs-tiled#118]
``` shell
>cargo test
...
test test_layer_property ... FAILED
...
```
/Per

**Comment by alexdevteam** [comment]
Byproduct of #110.

**Comment by PieKing1215** [comment]
Yeah this is because of line endings in multiline strings. Could either be fixed by normalizing line endings internally or doing it in the test.
@alexdevteam This comment is unclear to me (https://github.com/mapeditor/rs-tiled/pull/110#issuecomment-1002159357)
> Didn't notice this, it'd be better if you could normalize line endings from code

Do you mean it should be done in user code (ie. in the test) or in the library?

**Comment by alexdevteam** [comment]
> Do you mean it should be done in user code (ie. in the test) or in the library?

From tests, but maybe it is better to set gitattributes to use unix line endings on tmx files.

**Comment by alexdevteam** [comment]
Fixed by specifying line endings in gitattributes in #106.
