### ISSUE TITLE
object layer

### ISSUE THREAD

**Issue by aep** [mapeditor/rs-tiled#49]
any idea what to use for collision? object layer doesnt seem to be supported, so i wonder what everyone else is using instead.

or would it be worth implementing  object layer parsing?

**Comment by AberDerBart** [comment]
Object layers are supoorted, they are just not listed in `layers`, but in `object_groups`

**Comment by bjorn** [comment]
> Object layers are supoorted, they are just not listed in `layers`, but in `object_groups`

Yeah, this isn't very convenient though, since now the only way to know the layer order is by checking each layer type's `layer_index`, and it also will be tricky to support group layers this way (see #53). Would be a good idea to transition the various layer types to an enum.

But, closing this issue since in principle object layers are supported.
